### ISSUE TITLE
I am facing the error below when I trying to use prepare-alignments.py

### ISSUE THREAD

**Issue by gyq-123** [mailund/ziphmm#7]
File "prepare-alignments.py", line 60, in main
    alignments = SeqIO.to_dict(SeqIO.parse(inf,in_format))
  File "/pub/anaconda3/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line                                                                              607, in parse
    return iterator_generator(handle)
  File "/pub/anaconda3/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 1                                                                             83, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/pub/anaconda3/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", lin                                                                             e 52, in __init__
    raise StreamModeError(
Bio.StreamModeError: Fasta files must be opened in text mode.
(base) ug1231@gs40:~/gyq/ILS/1_taxa/final$ tail -n 20 nohup.out
  File "/pub/anaconda3/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line                                                                              607, in parse
    return iterator_generator(handle)
  File "/pub/anaconda3/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 1                                                                             83, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/pub/anaconda3/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", lin                                                                             e 52, in __init__
    raise StreamModeError(
Bio.StreamModeError: Fasta files must be opened in text mode.
python prepare-alignments.py /home/ug1231/gyq/ILS/1_taxa/final/chr9_85639001_866                                                                             39000.fa.gz fasta analysis/chr9_85639001_86639000.fa.gz.gz.ziphmm
Traceback (most recent call last):
  File "prepare-alignments.py", line 117, in <module>
    main()
  File "prepare-alignments.py", line 60, in main
    alignments = SeqIO.to_dict(SeqIO.parse(inf,in_format))
  File "/pub/anaconda3/lib/python3.8/site-packages/Bio/SeqIO/__init__.py", line                                                                              607, in parse
    return iterator_generator(handle)
  File "/pub/anaconda3/lib/python3.8/site-packages/Bio/SeqIO/FastaIO.py", line 1                                                                             83, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/pub/anaconda3/lib/python3.8/site-packages/Bio/SeqIO/Interfaces.py", lin                                                                             e 52, in __init__
    raise StreamModeError(
Bio.StreamModeError: Fasta files must be opened in text mode.

**Comment by mailund** [comment]
I can't seem to find a `prepare-alignments.py` file in this repo, but the error message seems to be coming from BioPython and not ZipHMM.
